### PR TITLE
:sparkles: IF-3990 Make compatible with python3

### PR DESCRIPTION
**Pull request by t-wata**
- Make compatible with python3
    - Import six package
    - Remove notations not supported by python3
- Add some patterns to .gitignore
- Resolve some warnings

### CODE REVIEW

**Comment by NaoShark** [comment]
```
[your-path]/eclsdk/ecl/dedicated_hypervisor/v1/usage.py

import urllib

def get_usage_histories(self, session, history_id, **kwargs):
    """Shows your Guest Image usage history information."""

    params = []
    for key in kwargs.keys():
        item = "%s=%s" % (str(key), urllib.quote(str(kwargs[key]))) \
            if key in ['from', 'to'] \
            else "%s=%s" % (str(key), str(kwargs[key]))
        params.append(item)
```
In function `get_usage_historyies`, `urllib.quote()` is used.
But, how to import `urllib.quote()` in python2 and python3 have different.

e.g.
import succeeds in python2
```
Python 2.7.11 (default, Jun  3 2019, 13:46:20) 

In [1]: from urllib import quote
```
import fails in python3
```
Python 3.7.4 (default, Jul 12 2019, 01:10:03) 

In [1]: from urllib import quote                                                                                                                                                                                                                                                                                                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ecaa22ac36c3> in <module>
----> 1 from urllib import quote

ImportError: cannot import name 'quote' from 'urllib' (/usr/local/lib/python3.7/urllib/__init__.py)
```

It can be imported by doing like `from urllib.parse import quote`.

Thanks.

**Comment by NaoShark** [comment]
```
[your-path]/eclsdk/ecl/dedicated_hypervisor/v1/usage.py

import urllib

def get_usage_histories(self, session, history_id, **kwargs):
    """Shows your Guest Image usage history information."""

    params = []
    for key in kwargs.keys():
        item = "%s=%s" % (str(key), urllib.quote(str(kwargs[key]))) \
            if key in ['from', 'to'] \
            else "%s=%s" % (str(key), str(kwargs[key]))
        params.append(item)
```
In function `get_usage_historyies`, `urllib.quote()` is used.
But, how to import `urllib.quote()` in python2 and python3 have different.

e.g.
import succeeds in python2
```
Python 2.7.11 (default, Jun  3 2019, 13:46:20) 

In [1]: from urllib import quote
```
import fails in python3
```
Python 3.7.4 (default, Jul 12 2019, 01:10:03) 

In [1]: from urllib import quote                                                                                                                                                                                                                                                                                                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ecaa22ac36c3> in <module>
----> 1 from urllib import quote

ImportError: cannot import name 'quote' from 'urllib' (/usr/local/lib/python3.7/urllib/__init__.py)
```

It can be imported by doing like `from urllib.parse import quote`.

Thanks.

**Comment by t-wata** [comment]
Thank you for your review comment!
I corrected it in the way you suggested. Please review again.

**Comment by NaoShark** [comment]
Looks good to me. Thank you for your help.

**Pull request merged**
